/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Probook 440 G2' at '17/10/08 23:32' with Gradle 2.14.1
 *
 * @author Probook 440 G2, @date 17/10/08 23:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
